# Generated by Django 5.2.4 on 2026-07-15 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('statut', models.CharField(choices=[('ACHETEUR', 'Acheteur'), ('VENDEUR', 'Vendeur')], max_length=10, verbose_name='Statut')),
                ('categorie', models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale')], max_length=10, verbose_name='Catégorie')),
                ('libelle', models.CharField(blank=True, max_length=255, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Demandeur',
                'verbose_name_plural': 'Demandeurs',
                'ordering': ['libelle', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DemandeurMorale',
            fields=[
                ('demandeur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demandeurs.demandeur')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('nom_representant', models.CharField(max_length=100, verbose_name='Nom du représentant')),
                ('prenom_representant', models.CharField(max_length=100, verbose_name='Prénom du représentant')),
                ('cin_representant', models.CharField(max_length=20, verbose_name='CIN du représentant')),
            ],
            options={
                'verbose_name': 'Demandeur — personne morale',
                'verbose_name_plural': 'Demandeurs — personnes morales',
            },
            bases=('demandeurs.demandeur',),
        ),
        migrations.CreateModel(
            name='DemandeurPhysique',
            fields=[
                ('demandeur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demandeurs.demandeur')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'Demandeur — personne physique',
                'verbose_name_plural': 'Demandeurs — personnes physiques',
            },
            bases=('demandeurs.demandeur',),
        ),
    ]
