# Generated by Django 5.2.4 on 2026-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeurs', '0002_alter_demandeur_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeurmorale',
            name='cin_representant',
            field=models.CharField(max_length=20, unique=True, verbose_name='CIN du représentant'),
        ),
    ]
