# Generated by Django 5.2.4 on 2026-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (DH/Kg)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='referentiels/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Référentiel',
                'verbose_name_plural': 'Référentiels',
                'ordering': ['-is_active', 'nom'],
            },
        ),
    ]
