# Generated by Django 5.2.4 on 2026-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_alter_referentiel_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referentiel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_referentiel_actif'),
        ),
    ]
