# Generated by Django 5.2.4 on 2026-07-15 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandeurs', '0001_initial'),
        ('referentiel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, verbose_name='Année')),
                ('dernier_numero', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro')),
            ],
            options={
                'verbose_name': 'Compteur de séquence',
                'verbose_name_plural': 'Compteurs de séquence',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_vente', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Code vente')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (DH/Kg)')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité (Kg)')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix total (DH)')),
                ('date_vente', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de vente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistrée le')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='demandeurs.demandeur', verbose_name='Demandeur')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='referentiel.referentiel', verbose_name='Référentiel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente', '-id'],
            },
        ),
    ]
