# Generated by Django 5.2.4 on 2026-07-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0002_alter_referentiel_is_active'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencecounter',
            name='referentiel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='referentiel.referentiel', verbose_name='Référentiel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequencecounter',
            name='annee',
            field=models.PositiveIntegerField(verbose_name='Année'),
        ),
        migrations.AddConstraint(
            model_name='sequencecounter',
            constraint=models.UniqueConstraint(fields=('annee', 'referentiel'), name='uniq_compteur_annee_referentiel'),
        ),
    ]
