# Generated by Django 5.2.4 on 2026-07-27 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_sequencecounter_referentiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='date_vente',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date de vente'),
        ),
    ]
